#! /bin/bash
#
# Copyright 2009-2016 Víctor M. Sánchez-Cartagena, Felipe Sánchez-Martínez, Universitat d'Alacant
#
# This file is part of ruLearn.
# ruLearn is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# ruLearn is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with ruLearn.  If not, see <http://www.gnu.org/licenses/>.
#


set -e -o pipefail

PYTHONLIBDIR=/home/vmsanchez/local/lib/python

DIR=""
SL="es"
TL="ca"
GENFILE=""
QUERY_DIR=""
INVERSE_PAIR=""
EVALUATION_CORPUS="/work/vmsanchez/rules/corpora/consumer-eroski.test"
USE_GZIP="no"

TAGSEQUENCESANDGROUPSSUFFIX=""

PYTHONHOME=""

APERTIUM_PREFIX=""
APERTIUM_SOURCES="$HOME/sources"

RICHATSFLAG=""

CURDIR=`dirname $0`
FULLCURDIR=`readlink -f $CURDIR`

COPYRULES=false

ONLY_GENERATE_XML=false
CHUNKS_OPTION=""

usage()
{
cat << EOF
Bla bla bla

EOF
}

USE_SHORT_RESTRICTIONS_INFIX=".shortrestrictions"

RBPE=false
RBPE_GENTRANSFER_FLAG=""
ALT_MODE_FOR_RBPE=""

while getopts “s:t:d:f:q:e:izx:h:p:u:clryokb” OPTION
do
     case $OPTION in
         s)
             SL=$OPTARG
             ;;
         t)
             TL=$OPTARG
             ;;
         d)
             DIR=$OPTARG
             ;;
         f)
             GENFILE=$OPTARG
             ;;
         q)
             QUERY_DIR=$OPTARG
             ;;
         e)
             EVALUATION_CORPUS=$OPTARG
             ;;
         i)
             INVERSE_PAIR="yes"
             ;;
         z)
                USE_GZIP="yes"
                ;;
        x)
                TAGSEQUENCESANDGROUPSSUFFIX=$OPTARG
                ;;
        l)
		USE_SHORT_RESTRICTIONS_INFIX=""
		;;
	r)
		USE_SHORT_RESTRICTIONS_INFIX=".fixed"
		;;
        h)
                PYTHONHOME=$OPTARG
                ;;
        p)
                APERTIUM_PREFIX=$OPTARG
                ;;
        u)
               APERTIUM_SOURCES=$OPTARG
               ;;
        c)
		RICHATSFLAG="--emptyrestrictionsmatcheverything"
		;;
        y)
		COPYRULES=true
		;;
	o)
	      ONLY_GENERATE_XML=true
	      ;;
	k)
	    CHUNKS_OPTION="--generatechunks"
	    ;;
	 b)
	    RBPE=true
	    RBPE_GENTRANSFER_FLAG="--rbpe"
	    ;;
         ?)
             usage
             exit
             ;;
     esac
done

TMPFILE1=`mktemp`
TMPFILE12=`mktemp`
TMPFILE2=`mktemp`
GENFILETEMP=""

#Not needed
#if $ONLY_GENERATE_XML ; then
#  DIR=`mktemp -d`
#  TAGSEQUENCESANDGROUPSSUFFIX="_${SL}-${TL}"
#fi


PAIR="$SL-$TL"
if [ "$INVERSE_PAIR" ]; then
	PAIR="$TL-$SL"
fi

if [ "$QUERY_DIR" == "" ]; then
	QUERY_DIR=`basename $GENFILE`
fi


GENFILETEMP=`mktemp`
if [ "$USE_GZIP" == "yes" ]; then
	zcat $GENFILE > $GENFILETEMP
	GENFILE=$GENFILETEMP
fi

mkdir -p $DIR/queries/$QUERY_DIR/experiment

NUMATS=`cat $GENFILE | wc -l `
CURAT=$NUMATS

while read line
do
	echo "$CURAT | $line"
	CURAT=`expr $CURAT - 1` || true
done < $GENFILE  > $DIR/queries/$QUERY_DIR/experiment/alignmentTemplatesGeneralisedResult.txt


EXPQUERIESDIR=$DIR/queries/$QUERY_DIR/experiment/
TAGGROUPS=$DIR/../config/taggroups$TAGSEQUENCESANDGROUPSSUFFIX

APERTIUMPATH=""
if [ "$APERTIUM_PREFIX" != "" ]; then
  TRANSFERTOOLSPATH="LD_LIBRARY_PATH=$APERTIUM_PREFIX/lib $APERTIUM_PREFIX/bin/"

else
  TRANSFERTOOLSPATH=""
fi

#ORIGINALAPERTIUMMODE=$APERTIUM_SOURCES/modes/${SL}-$TL.mode
ORIGINALAPERTIUMMODE=$APERTIUM_PREFIX/share/apertium/modes/${SL}-$TL.mode

INTERNALTL="$TL"
POSTTRANSFERRULES=$DIR/../config/apertium-${SL}-$TL.posttransfer.ptx
if [ $RBPE == true ]; then
ALT_MODE_FOR_RBPE=$APERTIUM_PREFIX/share/apertium/modes/${TL}-$SL.mode
INTERNALTL="${SL}_rbpe"
POSTTRANSFERRULES=$DIR/../config/apertium-${TL}-$SL.posttransfer.ptx
fi


BINBIDICTIONARY=$APERTIUM_SOURCES/apertium-$PAIR/${SL}-$TL.autobil${USE_SHORT_RESTRICTIONS_INFIX}.bin

cp $EXPQUERIESDIR/alignmentTemplatesGeneralisedResult.txt $EXPQUERIESDIR/alignmentTemplatesGeneralised.txt
mkdir -p $EXPQUERIESDIR/evaluation
mkdir -p $EXPQUERIESDIR/evaluation/paired_bootstrap
mkdir -p $EXPQUERIESDIR/rules
mkdir -p $EXPQUERIESDIR/modes

#sort ATs to be processed by the module which encodes them as Apertium rules
cat $EXPQUERIESDIR/alignmentTemplatesGeneralised.txt | /usr/bin/python $PYTHONLIBDIR/addGeneralisedLeftSide.py | LC_ALL=C sort -r | /usr/bin/python $PYTHONLIBDIR/uniqSum.py | awk -F"|" '{print $2"|"$1"|"$3"|"$4"|"$5"|"$6}' | sed 's_^ __' | sed 's_|\([0-9]\)_| \1_' |  LC_ALL=C sort -r | /usr/bin/python $PYTHONLIBDIR/removeExplicitEmptuTagsFromPatternTLandRest.py $RICHATSFLAG | awk -F"|" '{print $2"|"$3"|"$4"|"$5"|"$6}' | sed 's_^ __' > $EXPQUERIESDIR/rules/alignmentTemplates.txt
cat $EXPQUERIESDIR/rules/alignmentTemplates.txt | cut -f 1 -d '|' | uniq > $EXPQUERIESDIR/rules/alignmentTemplates.txt.patterns

#create Apertium rules
echo "${TRANSFERTOOLSPATH}apertium-gen-transfer-from-aligment-templates --input $EXPQUERIESDIR/rules/alignmentTemplates.txt --attributes $TAGGROUPS --generalise --nodoublecheckrestrictions --usediscardrule $RICHATSFLAG $CHUNKS_OPTION $RBPE_GENTRANSFER_FLAG | /usr/bin/python $PYTHONLIBDIR/addDebugInfoToTransferRules.py > $EXPQUERIESDIR/rules/rules.xml" > $TMPFILE1
/bin/bash $TMPFILE1

rm -f $TMPFILE1

echo "${TRANSFERTOOLSPATH}apertium-gen-transfer-from-aligment-templates --input $EXPQUERIESDIR/rules/alignmentTemplates.txt --attributes $TAGGROUPS --generalise --nodoublecheckrestrictions --usediscardrule $RICHATSFLAG $CHUNKS_OPTION $RBPE_GENTRANSFER_FLAG  > $EXPQUERIESDIR/rules/rules.nodebug.xml" > $TMPFILE12
/bin/bash $TMPFILE12

rm -f $TMPFILE12

if $ONLY_GENERATE_XML ; then
  cat $EXPQUERIESDIR/rules/rules.nodebug.xml
  #rm -R $DIR
else
  #compile rules
  ${APERTIUMPATH}apertium-preprocess-transfer $EXPQUERIESDIR/rules/rules.xml $EXPQUERIESDIR/rules/rules.bin

  if [ $COPYRULES ]; then
    cp $EXPQUERIESDIR/rules/rules.nodebug.xml $DIR/rules.result.xml
  fi

  if [ "$EVALUATION_CORPUS" == "" ]; then
    echo "No evaluation corpus provided. Rules will not be evaluated"
  else

  cp $EVALUATION_CORPUS.$SL $EXPQUERIESDIR/evaluation/source
  cp $EVALUATION_CORPUS.$INTERNALTL $EXPQUERIESDIR/evaluation/reference

  #use lexical selection if present in original mode
  LEXICAL_SELECTION_COMMAND=""
  NUMLINESWITHLRX=`cat $ORIGINALAPERTIUMMODE | ( grep "lrx-proc" || : ) | wc -l`
  if [ "$NUMLINESWITHLRX" != "0" ]; then
      LEXICALSELARGUMENT=`cat $ORIGINALAPERTIUMMODE | ( grep -v '^ *$' || : ) | awk -F'lrx-proc' '{ print $2}' | awk -F'|' '{print $1}'`
      LEXICAL_SELECTION_COMMAND="lrx-proc $LEXICALSELARGUMENT"
  fi

  #evaluate word for word
  ${APERTIUMPATH}apertium-preprocess-transfer /home/vmsanchez/local/lib/empty-rules-for-translating.t1x $EXPQUERIESDIR/rules/empty-rules-for-translating.t1x.bin

  /bin/bash /home/vmsanchez/local/lib/createModeNoRules.sh "$ORIGINALAPERTIUMMODE" "$TRANSFERTOOLSPATH" /home/vmsanchez/local/lib/empty-rules-for-translating.t1x $EXPQUERIESDIR/rules/empty-rules-for-translating.t1x.bin $POSTTRANSFERRULES $BINBIDICTIONARY "$LEXICAL_SELECTION_COMMAND" > $EXPQUERIESDIR/modes/${SL}-${INTERNALTL}_norules.mode

  cat $EXPQUERIESDIR/evaluation/source | /bin/bash /home/vmsanchez/local/lib/translate_apertium.sh "$APERTIUMPATH" ${SL}-${INTERNALTL}_norules join "" $EXPQUERIESDIR > $EXPQUERIESDIR/evaluation/translation_norules

  /bin/bash /home/vmsanchez/local/lib/mteval-v11b-nosgm.sh $EXPQUERIESDIR/evaluation/source $EXPQUERIESDIR/evaluation/reference $EXPQUERIESDIR/evaluation/translation_norules > $EXPQUERIESDIR/evaluation/evaluation_norules

  /bin/bash /home/vmsanchez/local/lib/calculateStatsForPairedBootstrapResampling.sh $EXPQUERIESDIR/evaluation/source $EXPQUERIESDIR/evaluation/translation_norules $EXPQUERIESDIR/evaluation/reference $EXPQUERIESDIR/evaluation/paired_bootstrap/stats_norules


  #evaluate provided rules
  /bin/bash /home/vmsanchez/local/lib/createModeWithLearnedRules.sh $ORIGINALAPERTIUMMODE "$TRANSFERTOOLSPATH" $EXPQUERIESDIR/rules/rules $POSTTRANSFERRULES $BINBIDICTIONARY "/usr/bin/python $PYTHONLIBDIR/removeDebugInfoFromTransfer.py" "$LEXICAL_SELECTION_COMMAND" "" "$ALT_MODE_FOR_RBPE" > $EXPQUERIESDIR/modes/${SL}-${INTERNALTL}_learned.mode

  cat $EXPQUERIESDIR/evaluation/source | /bin/bash /home/vmsanchez/local/lib/translate_apertium.sh "$APERTIUMPATH" ${SL}-${INTERNALTL}_learned join "" $EXPQUERIESDIR > $EXPQUERIESDIR/evaluation/translation_learnedrules 2> $EXPQUERIESDIR/evaluation/used_rules

  #translate and not remove unknown mark
  cat $EXPQUERIESDIR/evaluation/source | /bin/bash /home/vmsanchez/local/lib/translate_apertium.sh "$APERTIUMPATH" ${SL}-${INTERNALTL}_learned join "" $EXPQUERIESDIR --show_unknown > $EXPQUERIESDIR/evaluation/translation_learnedrules_withunknown

  /bin/bash /home/vmsanchez/local/lib/mteval-v11b-nosgm.sh $EXPQUERIESDIR/evaluation/source $EXPQUERIESDIR/evaluation/reference $EXPQUERIESDIR/evaluation/translation_learnedrules | grep "^NIST" | cut -f 9 -d ' ' > $EXPQUERIESDIR/evaluation/evaluation_learnedrules

	/usr/bin/java -jar /home/vmsanchez/local/lib/tercom.7.25.jar  -r $EXPQUERIESDIR/evaluation/reference.xml -h $EXPQUERIESDIR/evaluation/translation_learnedrules.xml | ( grep -F "Total TER:" || : ) | cut -f 3 -d ' ' > $EXPQUERIESDIR/evaluation/ter_learnedrules

  #BLock comment
  if [ "THIS BLOCK IS COMMENTED" == "" ]; then

  #compute segment level bleu
  /bin/bash /home/vmsanchez/local/lib/mteval-v13-nosgm-segments.sh $EXPQUERIESDIR/evaluation/source $EXPQUERIESDIR/evaluation/reference $EXPQUERIESDIR/evaluation/translation_learnedrules |  grep -F " on segment " | cut -f 8 -d ' ' > $EXPQUERIESDIR/evaluation/evaluation_learnedrules_forsentences

  paste $EXPQUERIESDIR/evaluation/evaluation_learnedrules_forsentences $EXPQUERIESDIR/evaluation/translation_learnedrules > $EXPQUERIESDIR/evaluation/translation_learnedrules_withbleu

  cat $EXPQUERIESDIR/evaluation/used_rules | grep -v "LOCALE:"  | grep -v '^0$'  | grep -v '^ww' | LC_ALL=C sort | uniq -c | sort -r -n -k 1,1 | sed 's_^ *__'   | while read line ; do FREQ=`echo "$line" | cut -f 1 -d ' ' `; ATNUM=`echo "$line" | cut -f 2 -d ' '`; AT=`head -n $ATNUM $EXPQUERIESDIR/rules/alignmentTemplates.txt | tail -n 1 `;MODAT=`echo "$AT" | sed 's_^[^|]*|__'`; ISNEWAT=0; echo "$FREQ $ISNEWAT $AT"  ; done > $EXPQUERIESDIR/evaluation/report_rules

  cat $EXPQUERIESDIR/evaluation/used_rules | grep -v "LOCALE:"  | ( grep '^ww' || : ) | sed 's_^ww__'  | LC_ALL=C sort | uniq -c | sort -r -n -k 1,1 | sed 's_^ *__'   | while read line ; do FREQ=`echo "$line" | cut -f 1 -d ' ' `; ATNUM=`echo "$line" | cut -f 2 -d ' '`; AT=`head -n $ATNUM $EXPQUERIESDIR/rules/alignmentTemplates.txt.patterns | tail -n 1 `;MODAT=`echo "$AT" | sed 's_^[^|]*|__'`; ISNEWAT=0; echo "$FREQ $ISNEWAT $AT"  ; done >> $EXPQUERIESDIR/evaluation/report_rules

  cat $EXPQUERIESDIR/evaluation/used_rules | ( grep -v "LOCALE:" || : ) | ( grep '^0$' || : ) | wc -l  >> $EXPQUERIESDIR/evaluation/report_rules

  cat $EXPQUERIESDIR/evaluation/report_rules | /usr/bin/python $PYTHONLIBDIR/addWordInforToReport.py  > $EXPQUERIESDIR/evaluation/report_rules_words

  cat $EXPQUERIESDIR/evaluation/report_rules_words | /usr/bin/python $PYTHONLIBDIR/summarizeReport.py  > $EXPQUERIESDIR/evaluation/report_rules_words_summarized

  /bin/bash /home/vmsanchez/local/lib/calculateStatsForPairedBootstrapResampling.sh $EXPQUERIESDIR/evaluation/source $EXPQUERIESDIR/evaluation/translation_learnedrules $EXPQUERIESDIR/evaluation/reference $EXPQUERIESDIR/evaluation/paired_bootstrap/stats_learnedrules



  #table with most frequent rules and examples of application. Similar steps

  echo "${TRANSFERTOOLSPATH}apertium-gen-transfer-from-aligment-templates --input $EXPQUERIESDIR/rules/alignmentTemplates.txt --attributes $TAGGROUPS --generalise --nodoublecheckrestrictions --usediscardrule $RICHATSFLAG $RBPE_GENTRANSFER_FLAG | /usr/bin/python $PYTHONLIBDIR/addDebugInfoToTransferRules-debug.py > $EXPQUERIESDIR/rules/rules-extradebug.xml" > $TMPFILE2
  /bin/bash $TMPFILE2

  ${APERTIUMPATH}apertium-preprocess-transfer $EXPQUERIESDIR/rules/rules-extradebug.xml $EXPQUERIESDIR/rules/rules-extradebug.bin
  /bin/bash /home/vmsanchez/local/lib/createModeWithLearnedRules.sh $ORIGINALAPERTIUMMODE "$TRANSFERTOOLSPATH" $EXPQUERIESDIR/rules/rules-extradebug $POSTTRANSFERRULES $BINBIDICTIONARY "/usr/bin/python $PYTHONLIBDIR/removeDebugInfoFromTransfer.py moredebug" "$LEXICAL_SELECTION_COMMAND" "" "$ALT_MODE_FOR_RBPE" > $EXPQUERIESDIR/modes/${SL}-${INTERNALTL}_extradebug.mode
  cat $EXPQUERIESDIR/evaluation/source | /bin/bash /home/vmsanchez/local/lib/translate_apertium.sh $APERTIUMPATH ${SL}-${INTERNALTL}_extradebug join "" $EXPQUERIESDIR > $EXPQUERIESDIR/evaluation/output-extradebug 2> $EXPQUERIESDIR/evaluation/debug-extradebug

  cat $EXPQUERIESDIR/evaluation/debug-extradebug | ( grep -v "^0" || : ) | ( grep -v "^LOCALE:" || : ) | ( grep -v "^SINGLESOURCE:" || : ) | ( grep -v "^SINGLETARGET:" || : ) > $EXPQUERIESDIR/evaluation/debug-extradebug-clean

  AUTOGEN=`cat $EXPQUERIESDIR/modes/${SL}-${INTERNALTL}_norules.mode | tr '|' '\n' | ( grep -F "autogen.bin" || : ) | awk -F '$' '{ print $2;}'|  sed 's_1 __' | sed "s:^'::" | sed "s:'[ ]*\$::"`;
  #check sed
  cat $EXPQUERIESDIR/evaluation/debug-extradebug-clean | ( grep -F "TARGET:" || : ) | sed 's_^TARGET: __' | sed 's_^$_EMPTY_' | ${APERTIUMPATH}lt-proc -g $AUTOGEN | sed 's_\(.*\)_\n\1\n_' > $EXPQUERIESDIR/evaluation/debug-extradebug-clean-tlsurface

  paste $EXPQUERIESDIR/evaluation/debug-extradebug-clean $EXPQUERIESDIR/evaluation/debug-extradebug-clean-tlsurface | /usr/bin/python $PYTHONLIBDIR/collapseSourcetarget.py | LC_ALL=C sort | uniq -c > $EXPQUERIESDIR/evaluation/debug-extradebug-clean-withtlsurface

  #cat $EXPQUERIESDIR/evaluation/report_rules_words | /bin/bash $CURDIR/createHTMLTableFromFrequentRules.sh $EXPQUERIESDIR/evaluation/debug-extradebug-clean-withtlsurface $EXPQUERIESDIR/rules/alignmentTemplates.txt > $EXPQUERIESDIR/evaluation/table.html

  #check seds
  cat $EXPQUERIESDIR/evaluation/debug-extradebug | ( grep -v "^LOCALE" || : ) | tr  '\n' '|' | tr -d ']' | tr -d ']' | sed 's_TARGET:\([^|]*\)|SOURCE:\([^|]*\)_[\2|\1]_g' | sed 's_SINGLETARGET:\([^|]*\)|SINGLESOURCE:\([^|]*\)_[\2|\1]_g'  | sed 's_\^.<sent>\$\]_^.<sent>$]\n_g' | sed -r 's_(^|\|)([0-9]+)\|\[_[\2|_g' > $EXPQUERIESDIR/evaluation/debug-segmented


  rm -f $TMPFILE2

	#end block comment
  fi


  fi
fi

if [ "$GENFILETEMP" != "" ]; then
	rm "$GENFILETEMP"
fi
